### ISSUE TITLE
Firewall - Juniper

### ISSUE THREAD

**Issue by Lenoraa** [dnif/extractors#195]
**Vendor / Product / Version**
Juniper SRX Firewall

**Product details**
- URL - [Juniper SRX Firewall](https://www.juniper.net/us/en/solutions/security/next-gen-firewall/#:~:text=SRX%20Series%20firewalls%20provide%20application,policies%2C%20giving%20you%20granular%20control.)

**Integration details**
Tell us how the product is going to get integrated with DNIF
- User Manual
- Protocol / Format being used - Syslog
- Configuration guide - [https://www.juniper.net/documentation/partners/dell/11.2-srx/junos-security-swconfig-security.pdf](https://www.juniper.net/documentation/partners/dell/11.2-srx/junos-security-swconfig-security.pdf)

**Is there a trial version / NFR version available**
- No

**Event format**
Tell us about the format in which events are available
- Syslog

**Event details**
What kind of events are we expecting to see
- Event source database
- Sample event logs - [https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/ref/command/show-firewall-log.html](https://www.juniper.net/documentation/us/en/software/junos/routing-policy/topics/ref/command/show-firewall-log.html)
- [https://www.juniper.net/documentation/en_US/junos-space18.2/topics/concept/junos-space-firewall-event-log-overview.html](https://www.juniper.net/documentation/en_US/junos-space18.2/topics/concept/junos-space-firewall-event-log-overview.html)

**Prospect streams available**
Tell us what kind of streams can be extracted from the events
- Firewall, Threat, Authentication, IAM, Configuration

**Additional details / screenshot**
- ![Screenshot]()

**Comment by GayatriBatteli** [comment]
This task has been completed.
