### ISSUE TITLE
Endpoint Security - OfficeScan XG

### ISSUE THREAD

**Issue by Lenoraa** [dnif/extractors#238]
**Vendor / Product / Version**
Trend Micro OfficeScan XG

**Product details**
- URL - [https://www.trendmicro.com/en_hk/business/products/user-protection/sps/endpoint/officescan.html](https://www.trendmicro.com/en_hk/business/products/user-protection/sps/endpoint/officescan.html)

**Integration details**
Tell us how the product is going to get integrated with DNIF
- User Manual - [Admin guide](https://www.agronomy.k-state.edu/documents/it-support/osce8.0betaadministratorsguide.pdf)
- Protocol / Format being used - Key Value pairs
- Configuration guide - [Reference](https://docs.rapid7.com/insightidr/trend-micro-officescan/)

**Is there a trial version / NFR version available**
- Yes

**Event details**
What kind of events are we expecting to see
- Reference document (Log guide/ Field description) - [Reference guide](https://docs.trendmicro.com/en-us/enterprise/officescan-xg-service-pack-1-server-online-help/managing-the-product/managing-the-product1/log-management.aspx)
- Sample log event (sanitized)

**Additional details / screenshot**
- ![Screenshot]()

**Comment by GayatriBatteli** [comment]
This task is completed.
