### ISSUE TITLE
Operating System - Winlogbeat

### ISSUE THREAD

**Issue by Lenoraa** [dnif/extractors#241]
**Vendor / Product / Version**
Windows OS - Winlogbeat 

**Product details**
- URL - [https://www.elastic.co/beats/winlogbeat](https://www.elastic.co/beats/winlogbeat)

**Integration details**
Tell us how the product is going to get integrated with DNIF
- User Manual
- Protocol / Format being used - JSON
- Configuration guide - [https://docs.dnif.it/docs/beats](https://docs.dnif.it/docs/beats)

**Is there a trial version / NFR version available**
- Yes

**Event details**
What kind of events are we expecting to see
- Reference document (Log guide/ Field description) - [https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-logging.html](https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-logging.html)
- Sample log event (sanitized)

**Additional details / screenshot**
- ![Screenshot]()

**Comment by GayatriBatteli** [comment]
This task is completed.
