### ISSUE TITLE
Firewall - Cisco Meraki

### ISSUE THREAD

**Issue by GayatriBatteli** [dnif/extractors#373]
**Vendor / Product / Version**
Tell us more about the product that needs an extractor.
Cisco Meraki

**Product details**
- URL - [Cisco Meraki](https://www.google.com/aclk?sa=l&ai=DChcSEwiZrJH-ieLyAhXHmGYCHc13D_EYABAJGgJzbQ&ae=2&sig=AOD64_2HM0ALkIPhX6t-pMSKOizXFfywcQ&q&nis=1&adurl&ved=2ahUKEwiRtIj-ieLyAhXPT30KHYcnAWUQ0Qx6BAgCEAE)

**Integration details**
Tell us how the product is going to get integrated with DNIF
- User Manual  - [Manual](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Server_Overview_and_Configuration)
- Protocol / Format being used - Syslog
- Configuration guide - [Config](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Server_Overview_and_Configuration)

**Is there a trial version / NFR version available**
- Trial version (if available) - [Yes](https://meraki.cisco.com/freemx/)

**Event format**
Tell us about the format in which events are available
- Syslog

**Event details**
What kind of events are we expecting to see
- Reference document (Log guide/ Field description) - [Document](https://documentation.meraki.com/General_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples#Meraki_MX_Security_Appliance)
- All unique log events (sanitized)

**Additional details / screenshot**
- ![Screenshot]()
-

**Note**
DNIF Extractor Support team shall evaluate this creation request. The submission of this Git issue is only a request to add new extractor on the Extractor roadmap.

**Comment by BodhiSaar** [comment]
DNIF Extractor Support team has analyzed this Creation request. This is prioritized for September and TAT for releasing this Extractor to customers will be 13 September 2021.

**Comment by GayatriBatteli** [comment]
This task is completed.
