### ISSUE TITLE
TREND MICRO: Delimiter in CEF format samples should be \t (tab) instead of \s (space)

### ISSUE THREAD

**Issue by aman1808** [dnif/extractors#7]
**Observation**: Delimiter in key-value format are spaces and there are values which contain spaces as well. Due to this, parsing faces irregularities in extractions.

**Source**: Trend Micro (Key-Value)

**Target**: Fetch proper CEF format logs which has tabs and spaces intact, so that the regex for k-v decoding can be validated

**Samples**:
> <133>Jul 24 2019 12:47:36 abcd CEF:0|Trend Micro|Apex Central|2019|AV:File cleaned|WORM_HILGIL.SMRP|3|deviceExternalId=3372 rt=Jul 24 2019 07:16:07 GMT+00:00 cnt=1 dhost=7777 act=File cleaned cn1Label=VLF_PatternNumber cn1=1525100 cn2Label=VLF_SecondAction cn2=1 cs1Label=VLF_FunctionCode cs1=Real-time Scan cs2Label=VLF_EngineVersion cs2=1006 cs3Label=CLF_ProductVersion cs3=14.0 cs4Label=CLF_ReasonCode cs4=virus log cs5Label=VLF_FirstActionResult cs5=File cleaned cs6Label=VLF_SecondActionResult cs6=N/A cat=1703 dvchost=abcd cn3Label=CLF_ServerityCode cn3=2 fname=wmimgmt.com filePath=F:\RECYCLER\ dst=10.88.99.203 fileHash=hhhhhh deviceFacility=Apex One

**Comment by GayatriBatteli** [comment]
We have modified the event details regex to capture all the fields.
Fields are parsing properly now.
